title: "Aljoša Milenković"
author: "Aljoša Milenković"

url: "https://aljosamilenkovic.github.io"
baseurl: ""   # must be empty for user-site repos

# Indent lines under description. Using "|" also works nicely.
description: |
  <img src="./ja.jpg" alt="Aljoša Milenković" style="max-width:200px;border-radius:50%;margin:0 auto 1em;display:block;">

  Hi there! I'm a linguist with research interests in phonology, historical linguistics, metrics, dialectology, computational and corpus linguistics.

permalink: "/:slug"

favicon: "./logo.png"

remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark"
  appearance_toggle: true
  back_home_text: "home.."
  date_format: "%Y-%m-%d"
  show_description: true
  show_navbar: true
  show_footer: true
  show_copyright: true
  show_projects: true
  show_blog: false
  show_old_projects: false
  show_misc_list: false
  show_reading_time: true
  show_tags: true
  home:
    title_projects: "Portfolio"
    title_misc_list: "Details"
    title_blog: "Blog"
    title_old_projects: "Old Projects"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
