title: "Aljoša Milenković"
author: "Aljoša Milenković"

url: "https://aljosamilenkovic.github.io"
baseurl: ""   # must be empty for user-site repos

# Indent lines under description. Using "|" also works nicely.
description: |
  <img src="./ja.jpg" alt="Aljoša Milenković" style="max-width:200px;border-radius:0;margin:0 auto 1em;display:block;">

  Welcome! I am a fifth-year PhD candidate in Linguistics at Harvard University, with research interests in phonology, historical linguistics, metrics, dialectology, and computational and corpus linguistics. My research examines probabilistic and cumulative patterns in language and poetic meter using corpus analysis and experiments, with the goal of building more empirically grounded formal models of phonology. My dissertation, <em>Metrical Grammar: Variation, Cumulativity, and Generalization</em>, brings together my longstanding interest in Slavic philology with my training in formal, computational, and statistical approaches to linguistics. I am fortunate to be advised by <a href="https://meluhha.com/index.html" target="_blank" rel="noopener">Kevin Ryan</a>, <a href="https://becker.phonologist.org" target="_blank" rel="noopener">Michael Becker</a>, and <a href="https://alekseinazarov.org" target="_blank" rel="noopener">Aleksei Nazarov</a>.


permalink: "/:slug"

favicon: "./logo.png"

remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark"
  appearance_toggle: true
  back_home_text: "home.."
  date_format: "%Y-%m-%d"
  show_description: true
  show_navbar: true
  show_footer: true
  show_copyright: true
  show_projects: false
  show_blog: false
  show_old_projects: false
  show_misc_list: false
  show_reading_time: true
  show_tags: true
  home:
    title_projects: "Research interests"
    title_misc_list: "Details"
    title_blog: "Blog"
    title_old_projects: "Old Projects"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
